#!/usr/bin/env bash 
#doing a special kind of ping

echo "5-is_the_host_on_the_network "
read user_input

if [ "$user_input" = "8.8.8.8" ]; then
	ping -c 5 "$user_input"
else
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
